// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Routes$ReactHooksTemplate = require("./Routes.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Routes$ReactHooksTemplate.make, {
          message: "Hello! Click this text."
        }), "index1");

/*  Not a pure module */
