// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");

function handleClick(_event) {
  console.log("clicked!");
  return /* () */0;
}

function Routes(Props) {
  var message = Props.message;
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  console.log(url);
  return React.createElement("div", {
              onClick: handleClick
            }, message);
}

var make = Routes;

exports.handleClick = handleClick;
exports.make = make;
/* react Not a pure module */
